// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddDateModified : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201312261120413_AddDateModified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c3W7bNhS+H7B3EHS1DVjsZOjQFc6G1G23Yk1S1OluC0aiHaIS6Ul0ljzbLvZIe4WR+qH5K4mSYrtZboqaFD8ekofnHJLny79//zP75S5NgluY5Yjg0/D4aBoGEEckRnh1Gm7o8vvn4S8/f/3V7HWc3gV/1N+d8O9YS5yfhjeUrl9MJnl0A1OQH6UoykhOlvQoIukExGRyMp0+nxxPJ5BBhAwrCGYfNpiiFBY/2M85wRFc0w1IzkkMk7wqZzWLAjW4ACnM1yCCp+Hbs/QliAg+egUoOGItKbyjYXCWIMCEWcBk6SnZ9CcuWSj6ZL2+ZtLR+6v7NSx6Pg3ngMIVye7lr9h3v8N7pYAVvc/IGmb0/gNcVm3fxmEwUdtN9IaimdSGd8/+h+kPJ2FwsUkScJ2wgiVIchgG6x9fLCjJ4K8Qw4xJF78HlMIM87awEL+ahhfrH7vNxE+T6QmfiQnAmFBA2UIbgmtisiWA8wzy7mt5edEVW1qLyO1YbPXREo0Axv+tQRY0Y8ocBm/QHYzfQbyiNwLlHNzVJcfPmEp/xIjpPmtEs41/rwtIenR88uyZX8ezyVY/m7WWpCnThSelVcQsTAabFb9VYv8dqh4Hu1t+A/mN53Tw5XXORvl79B06fIO+Jzlt19JmjI9Z4mtZpk2CWyfrAtyiVaHNlhGEwQeYFJX5DVqXPu+IV3yqNnzORMpI+oEkVQtR8ekKZCvIdZ/Yahdkk0V9rU0h2pOpkcU8iyi6FWr+krApB9hb48429IZkQ/W2DmEG4zyZT10ZU7DytWXN89HFgJ6D7HNM/sK7X4gLMs/zoUrNYqUrRBNvH3A82An06dY7Rmuy4eIw4bbj4gvdjlcVwlKrdryura18Z4mE3+jvWewS6X6nq0RXYNUgTVmrScIL7VIUNb4SfMxh5pagrNUk4IV2CYoamwSdvSsbw5Nz/TL8waM+fLYFp712rTUqVfZzrz1TbNKnTTN+RHqw"
                       + "W+91CtC4x7NO3b5BWU577L7hUeA7kNNiTZn68FkbPIMc8B2JPpMNHRFvhfBoaHub5/cgz/8iWTy/AXgFRxlPDbn7IH4Bkgc/w7kM9VmekwgV9kryHJ8cl+yvcRw0hsDlGGo3w0TeJBStExSxrk/D74yZcAEKL7QF3AbiKuhxqHuRS/wKJpDCgO9G/kQyB3kEYnMd2JzEaglzPDDjHgAk7HCd0wwgTE0vhXCE1iBpEl1r1NG5caEEvF7zCq4h5v6paQ269CvfP5j9i260yWqbm9lEUqYuOlafY5pVwjjUNOvYqOrgksWmntUFf6vKD1AxbSp2pmLasLv0W1/v7k+9ihC3cTnVU+pA06UGz1swflhsxvIdmCWU1mRRD78DB6aclyWw8th9kLZYFnlXm0Se8y59bm+Sd7BFSt/Pr4tZC5hVIhRv9/Wrva4DvMECUtVjIMhOjdtAwvDMhiZpKOLmysSozWcLRHWuNdqXqt3SuDz1Gm2LLdrSlC+vrW25C7TG0iqokku3idI31utGXSnaQi8hsJgjQ6/agi0JQl5vfaOqo+s8crH2rpFbw4EOAUGPket+XB65kHOccZc65xiz6aNavJT/WBW/JDUv5RpnjOUmcIzRdFctDst/jIqLkppXm7bzIOtDkjCUom42KbOfqoLZxJEmNTsH6zU7wElpU1VJsChzpubfL/yTotISYxLlltwoIa3oiZIMrKBWy1U7hsX1CE/Xugb8iDiPU+OzLm6h7srwDuZK1QazbsL/X7ldW/rYkcsCbqfyDRsd36PFQKFptSxNA56+BhKQWa4K5yTZpNgdCbhbK3dvMoxS4Ye3vX/TAbc13RHLCxoZqSzpjiDusmUQUWjizCbaKhnRjaESRiCoKlk3FXR7D28FtKVqFVit+udq+TDqJ57/ZQhR+JjUuMyKkpHKkl1uhPpEK2O4TrlulCJlSYYoCg5mG5UOd/geMhOQCqC2DWRv9jC7p35+kRHqMg8UcYxTcJyH"
                       + "OzeSfCmnbOiGy7oGtP+NbahSfhRFKIu6Y2wTeGSYbamHnSkTchRDUxZ5udwqMUbzuVVpdyQLjBNjTxbHcQTyNThGTkaB02ZvrK2eYsVHHiuWx8LhOmc72XZQOnuzQ3Zyh6+7VbKBDFUVdceQMgdkHKm4O5aZCyBDmrV+yEpSgA6sVPriiuQAE1VU+WGaE7ot9UOyvfnruLZvPEJ8kQKgBPmi1MMSFk/6ihksSnZvA9XLLjPary4ouwT01ae2oN3iSPklneUIpdxnmrPRyQa6HxelPn3Ecb4VdRKHQfhJo19Bmgtn3ETqnwi1ETeS2s3jrLoFbGdxGteC5SdhwGS/RTG/Elzc5xSmpUYs/kzmCSqOEfUH5wCjJWRaQD5DzkidTp/3Z4GKTLo8j5NDpYIiPvzWFMLhqXwx+0HHSuXrDVZa6xIE34IsugGZmTM7LEnWilukxH7hBMwHURWN+VPN3TcpuPv28aidzIW0qoea2+tLdbRC9lBklclYLHd/HqN9e02nzQM9cGLgg2wBNX36GvlPu07m67N0JpWvF8r/YTsr3DzXEPvQ7QZNl8Kg66NFOnvOblaO/e1KO+qI7nEvnKanKOpLi6L2Q+M5UP9xsJqmUG+6RBT9mDV4iBF3sWV6D9rBlhmIp7FlBqGNOnduBkxvGXUGjFNGb1aLD5JXLNvTbTkvkMxPrZc77cZr+KGg6rgrgC/Bpwv5Yl9kC5EMvFN+xS5Sxd25RYdIoWhlgW3TmXdN1PJU1JHUpCE38UFYBV8Qm6uRlVImCO+SPLIf/XC8CO9PN3bKMmkgYlkffA7E29RxhN59O3Pr0L2N42XuQL2N8yVOWit9nSxr9Gi0pOvK7VBJnC+dO2KsmQwGfbmstLX7RtJa+dzJzk3XhK1uGWA38J8cpLYmTpu1BxfPyMZ4cxLebMhW0oyNC+eiwtlArXQhG0nOyZGzodoJOrYZsIsralzzYBX74UlqBompkcOkaZBCJRiJoTUG71Df"
                       + "TCrlpo2k1Tol+yCfyQq7zc3b21AUql8DZdCRPjNICbVNpmT2jDm8mqbXNDx7Oo4eBmh5vA8/OA96oJl8w3yh9IfWmRfO0WoLwf/sOoaR4gXFN2/xktS+WJOo/kR/IYMUxMxFnmUULUFEWXUE87z4yzJ/gGRT3BFfw/gtvtzQ9YayIcP0OlF2MXfqTf0XHEhV5tnluvhjY2MMgYmJ+E3mJX65QUks5H5jufpyQPBooXow4GtJ+cPB6l4gXRDcEaiaPhHkXMF0nTCw/BIvAH9DcMnWPofqjM1eIbDKQJpXGNv27CdTvzi9+/k/dnEAECpgAAA="; }
        }
    }
}
