// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddPostsActiveColumn : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201309242043172_AddPostsActiveColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c3W7bNhS+H7B3EHS1DWjsZmjRFk6L1G23YE1S1GlvC0aiHaL68SQ6TZ5tF3ukvcJIUaL5K4mSbKtFboqaFD8ekh/POSTPyX///Dt7dRdH3i3McpQmJ/7jo6nvwSRIQ5SsTvwNXj565r96+fNPs7dhfOd9rr47pt+Rlkl+4t9gvH4xmeTBDYxBfhSjIEvzdImPgjSegDCdHE+nzyaPpxNIIHyC5Xmzj5sEoxgWP8jPeZoEcI03IDpPQxjlZTmpWRSo3gWIYb4GATzxz07j1yBIk6M3AIMj0hLDO+x7pxECRJgFjJaOkk2fU8l83ifp9S2RDt9f3a9h0fOJPwcYrtLsXvyKfPcXvJcKSNGHLF3DDN9/hMuy7VnoexO53URtyJsJbWj35H8J/v3Y9y42UQSuI1KwBFEOfW/99MUCpxn8AyYwI9KFHwDGMEtoW1iIX07Di/XTdjPxfDI9pjMxAUmSYoDJQmuCK2KSJYDzDNLuK3lp0RVZWoPIzVhk9dESDQBG/61AFjgjZPa9d+gOhu9hssI3HOUc3FUlj58QSn9KEOE+aYSzTVOvs8mWJvXkSeOYLMkDdyQxi51LZsVtlch/3VZpt6T9E+Q3jiOgK2IdAPs9OLddqa13+iHNcTOx6jE+ZZHrnpzWCW6crAtwi1YFAQ0j8L2PMCoq8xu0ZtbiiFZ8KfdoTkTK0vhjGpUteMWXK5CtIKVraqpdpJss6KogCtEetIMo5mmA0S2n+euUTDlInBl3usE3adaXt5Xx743zI2i8Qc30WQxWrrqsfj7aKNBzkH0N02/J/hfiIp3neV9SXyEcuU7a8ZMnzrJbNSl3hu3alH+hatOygutLWZtWtZWubS0R197d9btZIlX7t5XoCqxqpGG1iiS00CxFUeMqwaccZnYJWK0iAS00S1DUmCRobePIGB5M3PehlfdxeGry1DptHqOLJm2rTtQt9soDd4d3z0a7A97GAA17VmnV7TuU"
                       + "5bjD7uvvEr0HOS7WlNCHzlrvGaSA79Pga7rBA+KtUDIY2sHm+QPI829pFs5vQLKCg4yngty/R7sA0c4PNDZFfZrnaYAKfSVYji+Wu9q3SejVeqJsDJWZISJvIozWEQpI1yf+b9pM2AC5FdoCbv1hGfSxr1qRy+QNjCCGHt2N9KZ9DvIAhPo6kDkJ5RJieGBGLQCIyEkzxxlACdatFEoCtAZRnehKo5bGjQrF4dWaN3ANE2qf6tagTb/iYVzvn3ejTFbT3MwmApnacKw6TtRTQjtb1HNsUDrYZDHRs7ygbqR8D4opU7E3iinDbtNvddd5OHoVLm7tcsqHxZ6qS3aet2D0zFaP5TowgyutyCKfQXsOTDq2CmDs9DtKXSyKvK9NIs55mz6316p72CLM9tO7U9ICZqUIxRNw9fircoA2WEAsWwwEyalx60hollljkoLCL5B0jEp9NkCU51qtPaN2Q2N26tXaFlu0oSldXlNbtguUxsIqyJILl3rCN8ZbP5UUTa4XF5jPkcarJmdLgBDXW92o8uhaj5yvvW3kRneghUPQYeSqHRdHzuUcZtyMc5Yx6zaqwUq5j1WyS0JzJtcwY2SbwDJG3Vw1GCz3MUomSmhebtrWg6wOSVxR8rrZhAXRlAWziSXaZnYO1mtygBOib8oSb8FCb+aPFu6xNTHDmAS5IcSGS8t7wmkGVlCppdQOYXE9QqN+rgE9Is7DWPusjVmoutKsg75SlcKsmtD/l2bXFIV0ZNOA26l8R0ZH92gxUKhrLUNTj0ZBgQhkhqvCeRpt4sTuCdhbS3dvIoxU4Ya3vX9TAbc17RHZBY2IxEp0hNlEmV3NK9GWUnPgZHK0o45d6zsTxxQi1I43tpa7oQ1/wxYheOHh6McCcUQgVrILutkQqnOjiGE7S9pRiigZEaIoGA3pmVnrz3g95qUAaqK7udluuF49cogIVZkDCj8sSTjWI5QdSbz6krZfzZVYDdpId/LwhqSMMpGIwIra"
                       + "Y2xjRkSYbamDnmExIJKiYUXtMcoQEBGjLBqNnrAcD1zVhBY2UOA0aQljqwc/aqR+FDvq9OeK6bTWgizmZmM2KePnXPmALkKVRe0xhNdwEUcobo+lv2+LkHqtG7L00K0CS5WuuPzBW0flVW6Y+oRuS92QTO/YKq7pGweHmj9rSy41L22PxJ6pRRRWsn8dKF/g6L51eenWxn0uPzW5yAYDSC+eDAcW6Y5On41WOtD+YCb06SKO9f2jlTgEwk0a9VpNXzjtdk39hNOG37Ipt2mz8marOcFNu+pin/gekf0WhfSaa3GfYxgzRiz+juYRKpz26oNzkKAlJCxIv0KarDedPuueIMejw/I8jMaaJYfo8BvD4vqHp4XkBx4qPK0zGNPWDCS5BVlwAzI9HPM7T17byZIqKRjl3P0Sg7tfD0oPMY/MuKJyKKhrmpgRspEjOqacBVasUPccMDNzp9P6gY48qWonrJWjba+R+7SriVBdlk5Pg+qEMtIdOKiClvKabEPskqrUa7qk7KMuLJIyj4zbt8gzGsbwHCRh5MGP2JUfcZgkipGq49EyQkp8aGOgu+U1JH10oi1XofOgLbkKPfGUXIVeaIPOnT3/oLOMav6BVUbnnAIXJCfXsKN5sV516J8aryGalVd/H7vsuC2Aa3pFm9D3Q4W681DMvUa37yNQ1x4hMsYA9sYcnG0w6b7TZByJOhBNaiLDdhLT/R3l0tTmBLDwzH2G7h+GH5a3y8NxY68x/jVpMManiZFYm8qPULtvzpsZu7WxvCGN1NpY34yEtVLXybBGPwxL2q7cHklifZPbU76QHj+uLpcxaei+NmWIPcyRc9N1SlaXOdg12SeWlKK6jCJjD7YsD1O+kTXdyIRsTFkwZSLZEpFMoMZkDVOKkjVDyYRqTo8wzYBZXF5jmwej2LtPEdJSSGozSBQGSQHhQ+U+DZD1pW4mOeGhKUWmcUoOkfojEnYbRXawoUiJVjUJW5ZAj14kVDaZFIMy"
                       + "5PCqJKm64ZkDR1Q3QIkU3f3gHJKz9DARYguFv5ZMrHCOVlsI+reTExhIVpB/c5Ys08oWKxJVn6gPThCDkJjI0wyjJQgwqQ5gnhd/1+MziDbFHfE1DM+Syw1ebzAZMoyvI2kXU6Ne13+RgSbLPLtcF3/qaYghEDERvcm8TF5vUBRyud8Zrr4sENRbKB8M6Fpi+nCwuudIF2nSEqicPu7kXMF4HRGw/DJZAPqGYJOteQ7lGZu9QWCVgTgvMbbtyU9CvzC+e/k/61q2kO9bAAA="; }
        }
    }
}
