// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UpdateCategoryField : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201309222008092_UpdateCategoryField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1czW7cNhC+F+g7CDq1BeLduEiQBOsEziZpjcZ2kHVyDWiJuxYiUVuJ69jP1kMfqa9QUpQo/kqipP1J4EuQJcWPM+RwZjic8X///Dt7dZfE3i3M8ihFJ/7jo6nvQRSkYYRWJ/4GLx8981+9/Pmn2dswufM+V98d0+/ISJSf+DcYr19MJnlwAxOQHyVRkKV5usRHQZpMQJhOjqfTZ5PH0wkkED7B8rzZxw3CUQKLH+TnPEUBXOMNiM/TEMZ52U56FgWqdwESmK9BAE/8s9PkNQhSdPQGYHBERmJ4h33vNI4AIWYB46UjZdPnlDKfz0lmfUuow/dX92tYzHzizwGGqzS7F78i3/0F76UG0vQhS9cww/cf4bIcexb63kQeN1EH8mHCGDo9+R/Cvx/73sUmjsF1TBqWIM6h762fvljgNIN/QAQzQl34AWAMM0THwoL8chlerJ92W4nnk+kxXYkJQCjFAJON1ghXyCRbAOcZpNNX9NKmK7K1BpLbscjuR8toBDD6bwWywBkRZt97F93B8D1EK3zDUc7BXdXy+AkR6U8oIrJPBuFs0zbrbFKLSbPwpElCtuRBdiQyi5NLVsVtl8h/3XZpu0L7J8hvHDmgO2JlgP0eXbZdRVuf9EOa43bBasb4lMWuZ3LaRLhxsS7AbbQqBNDAge99hHHRmd9Ea2YtjmjHl/KM5oSkLE0+pnE5gnd8uQLZClJxTU29i3STBX0VREHag3YQyTzd4Js0GypxldkejPMj6KpRDexZAlauWqh5PbqovnOQfQ3Tb2j3G3GRzvO8mvZ1SjQAQM4gVxGOXRft+MkTZ9qtOpC7sXY9yL9Q9WDZwTWdrAer3kpLdqaI693+mtlMkaq3u1J0BVYN1LBehRLaaKai6HGl4FMOMzsFrFehgDaaKSh6TBR0tk6Ehwfj9H1o5V1ce9p8rF6Hx+hcSceql+gWZ+VBdiXHKsDRLRxqyQ72BLxNQDTuLaPTtO+i"
                       + "LMc9Tt9wl+g9yHGxp0R86KoNXkEK+D4NvqYbPCLeKkKjoe1tnT+APP+WZuH8BqAVHIWfCnL3Hu0CxFu/0NgU9Wmep0FU6CvBcnyxRFnfotBr9EQZD5WZISRvYhyt4yggU5/4v2krYQPkVqgGrP1hGfSxr1qRS/QGxhBDj55GGiOfgzwAob4PZE1CuYUYHphRCwBictPMcQYihHUrFaEgWoO4iXRlUEfjRoni8GrPG7iGiNqnpj3oMq94Gdfn59Moi9W2NrOJIExdZKy6TjSLhHa3aJaxUcXBRotJPMvQcqvIDxAxZSl2JmIK213mraKU+xOvwsVt3E75sjhQdcnOcw1G72zNWK6MGVxphRb5DjqQMenaKoCx2+9B6mKR5F0dEnHNu8xZh1V3cESY7aexUzICZiUJxeNt9WyrygAdsIBYthgRJLfG2pHQLLMmSQoKDyDpGJX6bIEo77XaeCbaLYPZrVcbWxzRlqF0e01j2SlQBgu7IFMuBPWEb4xRP1Uo2lwvTjBfI02u2pwtAULcb/Wgytx15pzvvY1zozvQwSHowblqx0XOOZ3j8M1kzsKzbqNarJQ7r5JdEoYzusbhkR0CC4+6uWoxWO48SiZKGF4e2s5MVpckrih532zC0l/KhtnEkiczOwfrNbnACXkzZYu3YEkz80cL96yYhGFMgtyQHMOp5TPhNAMrqPRS0Q5hER6h+TrXgF4R52GifdbFLFRTadZB36lKYVZD6P9Ls2vKHzqyacB6Kd8R7ugZLRiFutYyDPVo/hKIQWYIFc7TeJMguydgHy3F3kQYqcMNr46/qYB1T3dEFqARkViLjjCbKKureSXaVmoOnCwc3UTHrvWdBceU3NNNbmwjtyM2/A1bhOCN+xM/lkIjArGWbYibDaG6N4oYtrukHaXIbxEhioaDEXpm1oZLvJ6tUgC1ibt52HZkvb7miBj2y48dSQxaSQenIZjVgHagZ3B8E1Dmh0hbyJq6Y9TZHiJM3eqg"
                       + "IVj2hqQiWFN3jDJ5Q8Qomw7mhFsce9cDrj34Fzht59s46sEDOlAPiF1ShsuK6Z7VQVjMw7ZkDMoXb8kUlG0/ksyVT98iVNnUHUN4xxZxhObuWPrLtAip97ohS0/UKrDU6YrLn6p1VN7lhqkvaN3qhmR6gVZxTd84uML8QVpyhnlrdyT2wCyisJbd60A59KJ7xWW4rIvjW35qcm4NBpCGjAxXDSm6pq9GJx1of+oS5nQhx/py0YkcAuFGjRoQ0zdOi4upn3Cx4fExJQ42K2NS7UVlWpCKfeJ7hPbbKKQBqsV9jmHCJGLxdzyPo8Jprz44ByhaQiIF6VdIC+Sm02f9i9J4Xleeh/GhVqZFlP3WhLbhiWUh+YHHSizrDca0NQNBtyALbkCmJ1J+5wVjW9lSpXiiXLtfEnD3617FQ6zdMu6onMTpWpplhGyVER1Trrwqdqh/3ZVZcqfTZkYPvJBpK1KrFiD1WXi9/KgXyoGen1HVq1RPZGOxT4nQoOWSqn6uI/e9kyp+jIevqO8Zx2zspVDjwQvYlhewn+KF7ShTqeigz0E6WImQCg66mNd+9QRoiE601Qj0ZtpSIzAQT6kRGIQ26trZ8/5706jm/VtpdM7ld0Fycux6mhdroEL/1BhEaFdewz3kcuKuAK5lDV1SzveVYs5TIHeaVb6LBFl7ZsYhJo631r7USZy7Lk9xFNSRxKQhI2srudTfUQ1LYy4+S4vcZcr8fuTD8vK4P9nYaW59Q/mJ8WHhQKxN5Ueo07fXqxy6tbG8AB2otbG++Ah7pe6TYY9+GCnpunM7FBLri9qO6nT0vG11u4zFOveNpTrsWY3cm65TsrvMwW6o+rCU8jRV8hhnsFVXmOp8rGU+JmRjqYCpAshWAGQCNRZJmEqDrJVBJlRzWYJpBczk8h7bOhjJ3n5pjla60Vi5oUiQlIg9Vs3RCNVW6mGSCw3aSlNal2QfJTeiwNY5YHtjRSpwaiiUsqRpDBJC5ZBJGSRj"
                       + "slcVJzWxZ077UN0AJc9z+8w5FEXpSR7EFgp/X5hY4Txa1RD0rw0jGEhWkH9zhpZpZYsViqpP1AcniEFITORphqMlCDDpDmCeF39P4zOIN0WM+BqGZ+hyg9cbTFiGyXUsnWJq1JvmLyq/ZJpnl+viTyyNwQIhM6KRzEv0ehPFIaf7nSH0ZYGg3kL5YED3EtOHg9U9R7pIUUegcvm4k3MFk3VMwPJLtAD0DcFGW/sayis2exOBVQaSvMSox5OfRPzC5O7l/83JxdghWwAA"; }
        }
    }
}
