// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class UpdateTagPostFieldLengths : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201309221955457_UpdateTagPostFieldLengths"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c227cNhB9L9B/EPTUFoh37SJBGqxbOJukNRpfkHX6GtASd01El63Edexv60M/qb9QUpQoXiVR0l4S+CXIkuLhDGc4MyRn/N8//85+e4gj7x5mOUqTU//4aOp7MAnSECWrU3+Dl89e+r/9+v13s7dh/OD9VX13Qr8jI5P81L/DeP1qMsmDOxiD/ChGQZbm6RIfBWk8AWE6OZlOX06OpxNIIHyC5XmzD5sEoxgWP8jPeZoEcI03ILpIQxjlZTvpWRSo3iWIYb4GATz1z8/i1yBIk6M3AIMjMhLDB+x7ZxEChJgFjJaOlE1/oZT5fE4y61tCHX68eVzDYuZTfw4wXKXZo/gV+e5P+Cg1kKbrLF3DDD9+gMty7HnoexN53EQdyIcJY+j05H8J/vnE9y43UQRuI9KwBFEOfW/94tUCpxn8HSYwI9SF1wBjmCV0LCzIL5fh1fpFt5X4ZTI9oSsxAUmSYoCJoDXCFTKJCOA8g3T6il7adENEayC5HYtIHy3RCGD03wpkgTOizL73Dj3A8D1MVviOo1yAh6rlhGj0xwQR1SdjcLZpm3Q2qbWkWXfSOCYSeVIdicxi45JVcRMS+a+blLars3+A/M6RAyoRKwPs9+iq/dxRtfVJr9MctytWM8bHLHKk+3jaRLhxsS7BPVoVCmjgwPc+wKjozO/QmjmLI9rxqdyjOSEpS+MPaVSO4B2fbkC2glRdU1PvIt1kQV8DUZD2ZB1EMs82+C7Nhmpc5bUH43wLtmpU/3oeg5WrFWpejy6m7wJkn8P0S7J7QVym8zyvpn2dEgsAEmeQG4Qj56jk+XNn2q02kEexdjvIv1DtYNnBLZ1sB6veykp2pojb3f6W2UyRare7UnQDVg3UsF6FEtpopqLocaXgYw4zOwWsV6GANpopKHpMFHT2ToSHJ+f0dVjlHqHhcY/YsDHG6rV5jMGVtK16qW6xV550VwqsAozu4VBPdrA74G0M0LinjE7T"
                       + "vkNZjnvsvuEh0XuQ40KmRH3oqg1eQQr4Pg0+pxs8It4KJaOh7W2dr0Gef0mzcH4HkhUchZ8KcvcR7QJEWz/Q2Az1WZ6nASrsleA5PlkuWd8modcYiTIeKjdDSN5EGK0jFJCpT/2ftJWwAXIvVAPW8bAMeuyrXuQqeQMjiKFHdyO9Ip+DPAChLgeyJqHcQhwPzKgHABE5aeY4AyjBupdCSYDWIGoiXRnU0blRoji82vMGrmFC/VOTDLrMKx7G9fn5NMpita3NbCIoUxcdq44TzSqhnS2adWxUdbDRYlLP8mq5VeUHqJiyFDtTMYXtLvNWt5T7U68ixG0Up3xYHGi65OC5BqNntmYsV8YMobRCi3wGHciYdGwVwNjp9yBtsUjyrjaJuOZd5qyvVXewRZjvp3enZATMShKKt9vq1VbVATpgAbHsMRAkp8Y6kNA8s6ZJCgq/QNIxKvPZAlGea7XxTLVbBrNTrza22KItQ6l4TWPZLlAGC1KQKRcu9YRvjLd+qlK0hV6cYL5Gml61BVsChChvdaPK3HXmnMvexrkxHOgQEPTgXPXjIuecznH4Zjpn4Vn3US1eyp1XyS8Jwxld4/DINoGFR91dtTgsdx4lFyUMLzdtZyarQxI3lLxvNmHZL2XDbGJJk5ldgPWaHOCEtJmyxVuwnJn5s4V7UkzMMCZBbsiN4dTymXCagRVUeqlqh7C4HqHpOreAHhHnYax91sUtVFNp3kGXVGUwqyH0/6XbNaUPHdksYL2U7wh3dI8WjELdahmGejR9CUQgM1wVztNoEyf2SMA+Wrp7E2GkDje8+v5NBax7uiOyCxoRibXoCLOJsrpaVKKJUgvgZOXopjp2q++sOKbknm56Yxu5HbXhb9giBG/cn/qxFBoRiLVsQ91sCNW5UcSwnSXtKEV+iwhRNByM0jO3Nlzj9WyVAqhN3c3DtqPr9TFHxLAffuxI4qWVtHEaLrMa0A50D47vAsr8EEmErKk7Rp3tIcLU"
                       + "rQ4WgmVvSCaCNXXHKJM3RIyy6WB2uCWwd93g2oN/gdO2v42jniKgA42A2CFluK6YzlkdlMU8bEvOoHzxllxB2fYt6Vz59C1ClU3dMYR3bBFHaO6Opb9Mi5B6rxuy9EStAkudrrj8qVpH5V1umPqC1q1uSKYXaBXX9I1DKMwfpKVgmLd2R2IPzCIKa9m9DZSvXvSouLwu6xL4lp+agluDA6RXRoajhnS7pq9GJxtof+oS5nQhx/py0YkcAuFGjXohpgtOuxdTP+Fqw+/HlHuwWXkn1V5Tpl1SsU98j9B+j0J6QbV4zDGMmUYs/o7mESqC9uqDC5CgJSRakH6GtD5uOn3ZvyaN53XleRgdamEaouy3JrQNTywLyQ88VmJZbzBmrRlIcg+y4A5kWvnYV14vthWJKrUT5dL9EIOHH/eqHWLpllGgcg6na2WWEfJ5m47omHLhVSGh/mVXRqKK9McmRg+8jmkrWqvWH/VZeL36qBfKge6fUa2rVE5kY7FPhdCg5ZKKfm6Ru+ykgh+z16DlPeO4jb3UaTwFAXo1xTji3E/twnaMqVRz0GcjHaxGSPUGXdxrv3KCZIhNtJUI9GbaUiIwEE8pERiENura2dP+e9Oopv1baXRO5XdBcgrseroX6z2F/qnxDqHdeA2PkMuJuwK4VjV0yTjfV4Y5z4DcaVL5LvJj7YkZh5g33lr6Uudw7ro6xVFRR1KThoSsraRSf0UlLI2p+CwrcpcZ8/vRD8vD4/50Y6ep9Q3VJ8Z3hQPxNlUcoU7fXq5y6N7G8gB0oN7G+uAjyEqVk0FG34yWdJXcDpXE+qC2ozIdPW1bFZexVuexsVKHvaqRc9NtSqTLAuyGog9LJU9TIY9xBltxhanMx1rlY0I2VgqYCoBs9T8mUGONhKkyyFoYZEI1VyWYVsBMLu+xrYOR7O1X5miVG42FG4oGSXnYY5UcjVBspW4muc6grTKldUn2UXEjKmydArY3VqT6poY6KUuWxiAl"
                       + "VDaZlEAyJntVbVITe+asDzUMUNI8t8+cQ02UnuNBfKHw14WJF87Rqoagf2s4gYHkBfk358kyrXyxQlH1ifrgBDEIiYs8yzBaggCT7gDmefHnNP4C0aa4I76F4XlytcHrDSYsw/g2knYxdepN8xeFXzLNs6t18ReWxmCBkInoTeZV8nqDopDT/c5w9WWBoNFC+WBAZYnpw8HqkSNdpklHoHL5eJBzA+N1RMDyq2QB6BuCjbb2NZRXbPYGgVUG4rzEqMeTn0T9wvjh1/8B6yNfxx9bAAA="; }
        }
    }
}
