// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddSeoNameFields : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201311032135216_AddSeoNameFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c3W7bNhS+H7B3EHS1DVjsZOjQFc6G1G23YE1S1OluC0aiHaIS6Ul0mjzbLvZIe4WR+qH5K4mSYrtFboqaFD8ekofnHJLny3///Dv77T5NgjuY5Yjg0/D4aBoGEEckRnh1Gm7o8sfn4W+/fvvN7HWc3gd/1d+d8O9YS5yfhreUrl9MJnl0C1OQH6UoykhOlvQoIukExGRyMp0+nxxPJ5BBhAwrCGbvN5iiFBY/2M85wRFc0w1ILkgMk7wqZzWLAjW4BCnM1yCCp+H5WfoSRAQfvQIUHLGWFN7TMDhLEGDCLGCy9JRs+guXLBR9sl5fM+now/XDGhY9n4ZzQOGKZA/yV+y7P+GDUsCK3mVkDTP68B4uq7bncRhM1HYTvaFoJrXh3bP/YfrTSRhcbpIE3CSsYAmSHIbB+ucXC0oy+DvEMGPSxe8ApTDDvC0sxK+m4cX6524z8ctkesJnYgIwJhRQttCG4JqYbAngPIO8+1peXnTNltYicjsWW320RCOA8X9rkAXNmDKHwRt0D+O3EK/orUC5APd1yfEzptIfMGK6zxrRbOPf6wKSHh2fPHvm1/FsstXPZq0lacp04UlpFTELk8FmxW+V2H+HqseYu+UPkN96joCviHMA5e/RN9XwPfWO5LRdsZoxPmSJrzGYNglunaxLcIdWhQJaRhAG72FSVOa3aF26qSNe8bHaozkTKSPpe5JULUTFx2uQrSBXV2KrXZBNFvU1EIVoT9ZBFvMsouhOqPlLwqYcYG+NO9vQW5IN1ds66hiM8zVYvFHjg/MUrHxtWfN8dDGgFyD7FJPPePcLcUnmeT5UqVl4c41o4u0Djgc7gT7deodVTTZcxP9uOy6+0O14VSEstWrH69rayneWSPiN/p7FLpHud7pKdA1WDdKUtZokvNAuRVHjK8GHHGZuCcpaTQJeaJegqLFJ0Nm7sjE8Odcvwx981efFtuC01661RqXKfu61Z4pN+rRpxo9I"
                       + "D3brvU4BGvd41qnbNyjLaY/dNzwKfAtyWqwpUx8+a4NnkAO+JdEnsqEj4q0QHg1tb/P8DuT5Z5LF81uAV3CU8dSQuw/iFyB59DOcy1Cf5TmJUGGvJM/x0XEv/hrHQWMIXI6hdjNM5E1C0TpBEev6NPzBmAkXoPBCW8BtIK6CHoe6F7nCr2ACKQz4buSvGnOQRyA214HNSayWMMcDM+4BQMIO1znNAMLU9FIIR2gNkibRtUYdnRsXSsDrNa/gGmLun5rWoEu/8v2D2b/oRpustrmZTSRl6qJj9TmmWSWMQ02zjo2qDi5ZbOpZ3cm3qvwAFdOmYmcqpg27S7/19e7+1KsIcRuXUz2lDjRdavC8BeOHxWYs34FZQmlNFvXwO3BgynlZAiuP3Qdpi2WRd7VJ5Dnv0uf2JnkHW6T0/fy6mLWAWSVC8dxeP7TrOsAbLCBVPQaC7NS4DSQMz2xokoYibq5MjNp8tkBU51qjfanaLY3LU6/RttiiLU358tralrtAayytgiq5dJsofWO9btSVoi30EgKLOTL0qi3YkiDk9dY3qjq6ziMXa+8auTUc6BAQ9Bi57sflkQs5xxl3qXOOMZs+qsVL+Y9V8UtS81KuccZYbgLHGE131eKw/MeouCipebVpOw+yPiQJQynqZpMyYakqmE0cmU2zC7BeswOclOlUlQSLMs1p/uPCP48pLTEmUW5JZxLSip4oycAKarVctWNYXI/wDKsbwI+I8zg1PuviFuquDO9grlRtMOsm/P+V27VlfB25LOB2Kt+w0fE9WgwUmlbL0jTgGWcgAZnlqnBOkk2K3ZGAu7Vy9ybDKBV+eNv7Nx1wW9MdsbygkZHKku4I4i5bBhGFJs5soq2SEd0YKmEEgqqSdVNBt/fwVkBbdlWB1ap/rpaPo37i+V+GEIX7U+Myh0kGKkt2qbb1+VPGcJ1J3ShFgpEMURQcjNKX7nG4xpvpQgVQm7rbmz2OrtePJTJCXeaBIg5dCo7z"
                       + "KOZGkq/QlO3XcLXWgHagO3l8h1Ql6CiKUBZ1x9im28gw21IPO1OmzyiGpizycpBVGovmIavS7kgWGCfGniyO48Dia3CMDIoCp83eWFs9RXZfeWRXHuKG65ztHNpB6ezNDtnJHb7uVqkBMlRV1B1DeueXcaTi7ljmy70Madb6IStP+DqwUumLK57yTVRR5YdpTui21A/J9kKv49q+8QjxxYO9EuSLUg9LWDzAK2awKNm9DVSvpsxov7pO7BLQV5/agnaLI+VXapYjlHL7aM5GJxvofgqU+vQRx/my00kcBuEnjX5haC6ccW+ofyLURtwfaveEs+rOrp0maVzilZ+EAZP9DsX8Am/xkFOYlhqx+DuZJ6g4RtQfXACMlpBpAfkEOeVzOn3en2Yp8t7yPE4OlWuJ+PBbE/6GJ97F7AcdK/GuN1hprUsQfAey6BZkZobrsJRWK26RwPqFMxwfRVU0nk41d9+l4P77vaqdTDa0rqiaPOvLJbRC9tA9lSpYrFB/oqB9R0ynzQM9cObdo2itmp98g/ynXWfL9Vk6kyvXC+VAd+Cohl8hv7mG2IfPNmi6FIpaHy3S6Wl2s3Lsb1faUUf0aHshDT0FPl9a4LMfnsyB+o+D1TSF29IlouhHXcFDjLiLjtJ70A46ykA8jY4yCG3UuXNTTHrLqFNMnDJ600Z8kLxi2Z5uy3nnY35qvY9pN17DDwVVx10BfBk0XdgN+2IziGzbnRIYdpGL7U7eOUSOQivNapsvvGsmlKeijqQmDcl/j5K2/wXRpRppH2UG7i7ZGfvRD8cj7v50Y6c0jgamk/WN5kC8TR1H6N23U6MO3ds4HtMO1Ns4H8+ktdLXybJGX42WdF25HSqJ83FyR5QwkyKgL5eVF/bQyAorXyjZuemGsNUtA+wGgpGDNdZEGrP24CLy2ChlTkaZDdnKSrGRzVxcMxuolY9jY6E5SWg2VDsDxjYDdnFFjWserGI/PgvMYAk1koQ0DVJy9Uei"
                       + "QI1B7NM3k8ppaWNBtU7JPthdssJu0+n2NhSFS9fAyXNkvAxSQm2TKck4Yw6v5sE1Dc+eQaOHAVrq7eMPzoN/Z+bLMF8o/fFx5oVztNpC8D9FjmGkeEHxzTlektoXaxLVn+gvZJCCmLnIs4yiJYgoq45gnhd/uuUvkGyKO+IbGJ/jqw1dbygbMkxvEmUXc6fe1H9BMlRlnl2ti7/mNcYQmJiI32Re4ZcblMRC7jeWqy8HBI8WqgcDvpaUPxysHgTSJcEdgarpE0HONUzXCQPLr/AC8DcEl2ztc6jO2OwVAqsMpHmFsW3PfjL1i9P7X/8HlQivcz5fAAA="; }
        }
    }
}
