// <auto-generated />
namespace IAmBacon.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class AddActiveCommentField : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201401121153590_AddActiveCommentField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAO1c3W7bNhS+H7B3EHS1DWjsZGjRFk6L1G23Yk1S1GlvC0aiHaGS6El0mjzbLvZIe4WR+qH4K5GSYrtpboqaFD8ekofnHJLny3///Dt7eZPE3jXM8gilx/7hwdT3YBqgMEpXx/4GLx899V+++Pmn2ZswufE+198d0e9IyzQ/9q8wXj+fTPLgCiYgP0iiIEM5WuKDACUTEKLJ0XT6dHI4nUAC4RMsz5t93KQ4SmDxg/ycozSAa7wB8SkKYZxX5aRmUaB6ZyCB+RoE8Nh/d5K8AgFKD14DDA5ISwxvsO+dxBEgwixgvHSUbPqMSuazPkmvb4h0+Pbidg2Lno/9OcBwhbJb/ivy3V/wViggRR8ytIYZvv0Il1Xbd6HvTcR2E7kha8a1od2T/6X49yPfO9vEMbiMScESxDn0vfWT5wuMMvgHTGFGpAs/AIxhltK2sBC/mobn6yd2M/FsMj2iMzEBaYowwGShFcElMckSwHkGafe1vLTogiytRuRuLLL60TIaAYz+W4MscEaU2ffeRjcwfA/TFb5iKKfgpi45fExU+lMaEd0njXC2ce91AVGPjo8eP3breDZp9LNda1GSEF14UFpBzJMAR9dskV4hFEOQOq91YXjI3LqtNfnvUCXb2z33J8ivHKeDKolxNsrfo+/z4dv8A8pxt663Y3zKYlf7NG0TXDtZZ+A6WhV7QjMC3/sI46Iyv4rWpec8oBVfKrORE5EylHxEcdWCVXy5ANkKUt1HutoF2mRBX5tViPZgsMY3WCcbfIWyoXpbB0KDcR7Mp6yMCVi52rL2+bAxoKcg+xqib+n2F+IMzfN8qFKTiOsiwrGzDzgc7AT6dOsc6bXZcHYkMdtx9oVsx6sKZqlFO17X1lbeWiLmN/p7Fr1Est+xlegCrFqkKWslSWihXoqixlWCTznMzBKUtZIEtFAvQVGjk8Dau5IxPDjX78Mf3OsjbFdw2mvXaqNSYT/32jPFJn3YNONH"
                       + "pHu79d4kIBr3eGbV7dsoy3GP3Tc8CnwPclysKVEfOmuDZ5ACvkfBV7TBI+KtonQ0tJ3N8weQ599QFs6vQLqCo4ynhtx+EL8A8Z2f4UyG+iTPURAV9orzHF8MV/Vv0tBrDYHLMdRuhoi8iXG0jqOAdH3s/6bMhAmQeaEGsAnERdBDX/Yi5+lrGEMMPbob6UPLHOQBCNV1IHMSiiXE8cCMegAQk8N1jjMQpVj1UlEaRGsQt4kuNbJ0blQoBi/XvIZrmFL/1LYGNv3y9w9q/6wbabK65mY24ZTJRsfqc0y7SiiHmnYdG1UdTLLo1LN6JuhU+QEqJk3F1lRMGrZNv/X17u7UqwhxW5dTPKUONF1i8NyA0cNiO5brwDShtCSLePgdODDhvMyBlcfuvbTFvMjb2iT8nNv02dwkb2GLlL6fXheTFjCrRCgyAOq3f1kHaIMFxKLHiCA5NTaBhOKZFU2SUNjNlYpRm88OiOpcq7QvVbujcXnqVdoWW7SjKV1eXdtyF0iNuVUQJeduE7lvtNeNslJ0hV5MYDZHil51BVscBL/e8kYVR2c9crb2ppFrwwGLgKDHyGU/zo+cyTnOuEudM4xZ9VEdXsp9rIJf4pqXco0zxnITGMaouqsOh+U+RsFFcc2rTWs9yPqQxAwlq5tNyhyqqmA2MSRbzU7Bek0OcFzyVVXiLcrMq/mjhXtqVVJiTIJck2HFpGU9YZSBFZRqqWqHsLgeoUlfl4AeEedhonxm4xbqrhTvoK5UbTDrJvT/ldvVJaEdmCxgM5VvyejoHi0GClWrpWnq0SQ4EINMc1U4R/EmSc2RgLm1cPfGwwgVbnjN/ZsM2NTYI5YXNDxSWWKPwO6yeRBWqOLMJtIqKdGNohJKICgqmZ0Kmr2HswLqEr4KrE79M7W8G/WrL5B5hLrMHoUlEfAwrPA+bYYyt4pHKku2uZ3qczGPYTorm1GKxCceoijYm81Yuu3hO1FNYyqAurahvtk+78HmMCjg"
                       + "GI+IZiT+ak/Y0C1Xfi1oP4xtqBKHBEUoi+wxmjQgHqYpdbAzZVqPYGjKIifHXaXXSJ67KrVH0sAYMXZkcQwHKVeDo2R2FDhd9kbb6iHivOcRZ3m4HK5zuvOxhdLpm+2zk9t/3a1SFnioqsgeg8s/4HG4YnssNaOAh1Rr3ZCF1AIZWKh0xWUpBioqq3LDVCe0KXVD0mUOyLi6bxxCfJZIIAT5rNTBEhaJAYIZLEq2bwPFKzM12q+uOW0C+upTXdCucaT0qk9zhBJuRdXZsLKB5idKrk8XcYwvTlbiEAg3aeSLTHXhlPtM+ROmNuxeU7q/nFV3id2MUuVysfzE94js11FILxYXtzmGSakRi7/jeRwVx4j6g1OQRktItAB9hZQdO50+7c9IZfl4eR7G+0pLjejwOxMRhycEhuQHHishsDdYaa1LkPQaZMEVyNTM22GptlrcIrH2OyeD3omqiBmolxEeykCqZv+XBNz8en8Ul+dkahVMzDF2pVxqIXtsBZFRWShMfz6lfoNOp+0D3XOC4p5uIplU2GfpVEphL5QfYTsLHEHTEPvQ/gZNl8Dk66NFMotPb1YO3e1KN+qIDnYn3KqHOOx7i8N2QyfaU/+xt5omUIBsIop+DJ90iBE3sXZ6D9rA2hmIJ7F2BqGNOndmJk5vGWUmjlFGZ3aNC5JTLNvTbRmvoNRPtddD3cZr+KGg6tgWwJVoZEMC2RXpgyUlb5XnsY2UdXOO0z5SOTrZaE1a9bYJY46KOpKatORI3gm74TtilbWyY8pE5W2SWHajH4Y35d3pxlbZLi2EMO2T0Z54mzqOkLvvZpDtu7cxvO3tqbcxvuVxayWvk2aN7o2W2K7cFpXE+Fa6JeacyqSQl0tLn7ttJc+VD6bk3HSJyOqWAXYLD8tArmvj1ml7MPGddMw7I/FOh6wl7+g4eSZKng5US1vSkfWMXD0dqp4opJsBvbisxjQPWrHvniynkKlauVSSBgmUBnsSVfvARuA/"
                       + "yptJpP60DdBqSnZBguMVtsnu29lQBMphC3XRkIAzSAmlTSbkBo05vJou2DY8fUKPHAZImcB3PzgHmqKavkN8Ifdn44kXzqNVA0H/iHwKA8ELsm/epUtU+2JJovoT+YUMYhASF3mS4WgJAkyqA5jnxV+4+QziTXFHfAnDd+n5Bq83mAwZJpexsIupU2/rv+BiijLPztfFHz0bYwhEzIjeZJ6nrzZRHDK532quvgwQNFqoHgzoWmL6cLC6ZUhnKLUEqqaPBTkXMFnHBCw/TxeAviGYZOueQ3HGZq8jsMpAklcYTXvyk6hfmNy8+B/10OHA+GAAAA=="; }
        }
    }
}
